### ISSUE TITLE
Decide on groupId

### ISSUE THREAD

**Issue by io7m** [LWJGL/lwjgl3-osgi#4]
Right now, the bundles are using a provisional `com.io7m.bundles` groupId. This obviously needs to be changed to something else prior to pushing to Central.

**Comment by darxriggs** [comment]
Thanks for your effort in providing OSGI bundles.

Do you know when the 1st release will be available? I am really looking forward to.

**Comment by io7m** [comment]
Hello!

I'll be pushing these to Central on the day after the next LWJGL release. We need to decide on a `groupId` to use, but there are no other barriers to release.

**Comment by darxriggs** [comment]
Wow that was fast. Sounds great. I'll ask the LWJGL guys about the next release date.

**Comment by Spasi** [comment]
The current 3.1.2 snapshot is a release candidate. I'm giving it a few more days for users to report any issues.

**Comment by io7m** [comment]
@Spasi: Might I suggest `org.lwjgl.osgi`?

I obviously don't need or want permissions on Sonatype to push to the entirety of `org.lwjgl.*` so `org.lwjgl.osgi` would be a straightforward way to put these OSGi bundles into their own partition. The `osgi` suffix would be extremely unlikely to conflict with any future additions to LWJGL.

The Maven dependencies would look like:

```
<dependency>
  <groupId>org.lwjgl.osgi</groupId>
  <artifactId>org.lwjgl.opengl</artifactId>
  <version>3.1.2</version>
</dependency>
```

... Which would be fairly unsurprising for anyone familiar with OSGi and Maven.

**Comment by Spasi** [comment]
I agree, lets go with `org.lwjgl.osgi`. It's the cleanest solution.

We'll also add an `OSGi` toggle in the [build configurator](https://www.lwjgl.org/download) to make the generated scripts use the new `groupId`.

**Comment by io7m** [comment]
I've just pushed `3.1.2` to Central, but it may take a few hours for Sonatype to enable syncing and for the syncing to actually take place.
